// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgBk6Tsx1xb9tVOct7ROMIYlqhlRATwoo',
    appId: '1:1013938444248:web:4d7ce4c62d1738e7f804ad',
    messagingSenderId: '1013938444248',
    projectId: 'medicine-finder-3ae5a',
    authDomain: 'medicine-finder-3ae5a.firebaseapp.com',
    storageBucket: 'medicine-finder-3ae5a.firebasestorage.app',
    measurementId: 'G-SMQVFBWJQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt7IKK6Cw1NKE-4rcztgZfXxBOEmy--0o',
    appId: '1:1013938444248:android:78faa02d393642a8f804ad',
    messagingSenderId: '1013938444248',
    projectId: 'medicine-finder-3ae5a',
    storageBucket: 'medicine-finder-3ae5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApymp5a75Xa0HoqPpVqrRsUkzp0cimNCU',
    appId: '1:1013938444248:ios:c2fefbbe82b808a2f804ad',
    messagingSenderId: '1013938444248',
    projectId: 'medicine-finder-3ae5a',
    storageBucket: 'medicine-finder-3ae5a.firebasestorage.app',
    iosBundleId: 'com.example.emergencyMedicineFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApymp5a75Xa0HoqPpVqrRsUkzp0cimNCU',
    appId: '1:1013938444248:ios:c2fefbbe82b808a2f804ad',
    messagingSenderId: '1013938444248',
    projectId: 'medicine-finder-3ae5a',
    storageBucket: 'medicine-finder-3ae5a.firebasestorage.app',
    iosBundleId: 'com.example.emergencyMedicineFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgBk6Tsx1xb9tVOct7ROMIYlqhlRATwoo',
    appId: '1:1013938444248:web:8f83c1c4d3614b95f804ad',
    messagingSenderId: '1013938444248',
    projectId: 'medicine-finder-3ae5a',
    authDomain: 'medicine-finder-3ae5a.firebaseapp.com',
    storageBucket: 'medicine-finder-3ae5a.firebasestorage.app',
    measurementId: 'G-VFP43MEPX1',
  );
}
